#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/nodes
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/nodes/Makefile,v 1.20 2008/02/19 10:30:07 petere Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/mbt
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = hashmap.o pgvector.o sha256.o vibuilder.o mbtree.o

include $(top_srcdir)/src/backend/common.mk
